logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
#      defaultZone: http://registry:8761/eureka/
      defaultZone: http://localhost:8761/eureka/


security:
  oauth2:
    resource:
#      user-info-uri: http://auth-service:5000/uaa/users/current
      user-info-uri: http://localhost:5000/uaa/users/current
#spring:
#  data:
#    mongodb:
#      uri: mongodb://user:root@localhost:27017/database_name
spring:
  rabbitmq:
#    host: rabbitmq
    host: localhost
